module.exports = [
  {
    id: "jjajangmyeon",
    name: "짜장면",
    category: "면류",
    price: 5000,
    description: "달콤짭짤한 사장님표 춘장 소스 짜장면",
  },
  {
    id: "jjamppong",
    name: "짬뽕",
    category: "면류",
    price: 6000,
    description: "얼큰하고 시원한 해물 짬뽕",
  },
  {
    id: "samsun-jjajang",
    name: "삼선짜장",
    category: "면류",
    price: 7000,
    description: "해삼, 새우, 오징어 듬뿍 들어간 고급 짜장",
  },
  {
    id: "samsun-jjamppong",
    name: "삼선짬뽕",
    category: "면류",
    price: 8000,
    description: "해물이 가득한 얼큰한 삼선짬뽕",
  },
  {
    id: "fried-rice",
    name: "볶음밥",
    category: "밥류",
    price: 6500,
    description: "고슬고슬 계란 볶음밥",
  },
  {
    id: "gochu-japchae-rice",
    name: "고추잡채밥",
    category: "밥류",
    price: 7000,
    description: "매콤한 고추잡채를 얹은 덮밥",
  },
  {
    id: "mapo-tofu-rice",
    name: "마파두부덮밥",
    category: "밥류",
    price: 7000,
    description: "얼얼하고 진한 마파두부 소스 덮밥",
  },
  {
    id: "tangsuyuk-small",
    name: "탕수육 (소)",
    category: "요리",
    price: 15000,
    description: "바삭한 튀김에 새콤달콤 소스, 2~3인분",
  },
  {
    id: "tangsuyuk-large",
    name: "탕수육 (대)",
    category: "요리",
    price: 22000,
    description: "바삭한 튀김에 새콤달콤 소스, 4~5인분",
  },
  {
    id: "kkanpunggi",
    name: "깐풍기",
    category: "요리",
    price: 16000,
    description: "매콤 달콤 바삭한 닭튀김 요리",
  },
  {
    id: "yuringgi",
    name: "유린기",
    category: "요리",
    price: 16000,
    description: "새콤달콤 특제 소스를 곁들인 담백한 닭튀김",
  },
  {
    id: "fried-mandu",
    name: "군만두",
    category: "사이드",
    price: 5000,
    description: "바삭하게 튀긴 손만두 8알",
  },
  {
    id: "cola",
    name: "콜라",
    category: "음료",
    price: 1500,
    description: "탄산 음료 355ml",
  },
  {
    id: "cider",
    name: "사이다",
    category: "음료",
    price: 1500,
    description: "탄산 음료 355ml",
  },
];
