module.exports = [
  // 식사
  {
    id: "jjajangmyeon",
    name: "짜장면",
    category: "식사",
    price: 7500,
    description: "달콤짭짤한 춘장 소스 짜장면",
  },
  {
    id: "jjamppong",
    name: "짬뽕",
    category: "식사",
    price: 9500,
    description: "얼큰하고 시원한 해물 짬뽕",
  },
  {
    id: "gan-jjajang",
    name: "간짜장",
    category: "식사",
    price: 9500,
    description: "국물 없이 볶아낸 진한 짜장 소스",
  },
  {
    id: "chadol-jjamppong",
    name: "차돌짬뽕",
    category: "식사",
    price: 13500,
    description: "차돌박이를 더한 얼큰한 짬뽕",
  },
  {
    id: "samsun-jjamppong",
    name: "삼선짬뽕",
    category: "식사",
    price: 13500,
    description: "해물이 푸짐하게 들어간 짬뽕",
  },
  {
    id: "fried-rice",
    name: "볶음밥",
    category: "식사",
    price: 9500,
    description: "고슬고슬 계란 볶음밥",
  },
  {
    id: "jaengban-jjajang",
    name: "쟁반짜장",
    category: "식사",
    price: 11500,
    description: "고기와 야채를 듬뿍 볶아 넓은 쟁반에 비벼 먹는 짜장",
  },
  {
    id: "shrimp-fried-rice",
    name: "새우볶음밥",
    category: "식사",
    price: 10500,
    description: "탱글한 새우를 넣은 볶음밥",
  },
  {
    id: "baek-jjamppong",
    name: "백짬뽕",
    category: "식사",
    price: 13500,
    description: "맵지 않고 시원한 백짬뽕",
  },
  {
    id: "japchae-rice",
    name: "잡채밥",
    category: "식사",
    price: 10500,
    description: "잡채를 얹은 덮밥",
  },
  {
    id: "gochu-japchae-rice",
    name: "고추잡채밥",
    category: "식사",
    price: 13500,
    description: "매콤한 고추잡채를 얹은 덮밥",
  },
  {
    id: "yusanseul-rice",
    name: "유산슬밥",
    category: "식사",
    price: 14500,
    description: "고기와 해물이 어우러진 유산슬 소스 덮밥",
  },
  {
    id: "japtang-rice",
    name: "잡탕밥",
    category: "식사",
    price: 16500,
    description: "고기와 해물을 푸짐하게 넣은 잡탕 덮밥",
  },
  {
    id: "mapo-rice",
    name: "마파밥",
    category: "식사",
    price: 10500,
    description: "얼얼하고 진한 마파두부 소스 덮밥",
  },
  {
    id: "jjamppong-rice",
    name: "짬뽕밥",
    category: "식사",
    price: 9500,
    description: "얼큰한 짬뽕 국물에 밥을 곁들인 메뉴",
  },
  {
    id: "chadol-jjamppong-rice",
    name: "차돌짬뽕밥",
    category: "식사",
    price: 13500,
    description: "차돌박이 짬뽕 국물에 밥을 곁들인 메뉴",
  },
  {
    id: "samsun-jjamppong-rice",
    name: "삼선짬뽕밥",
    category: "식사",
    price: 13500,
    description: "해물 삼선짬뽕 국물에 밥을 곁들인 메뉴",
  },
  {
    id: "baek-jjamppong-rice",
    name: "백짬뽕밥",
    category: "식사",
    price: 13500,
    description: "맵지 않은 백짬뽕 국물에 밥을 곁들인 메뉴",
  },

  // 반반메뉴
  {
    id: "tang-ja",
    name: "탕자",
    category: "반반메뉴",
    price: 12500,
    description: "탕수육 + 짜장면 반반",
  },
  {
    id: "tang-jjam",
    name: "탕짬",
    category: "반반메뉴",
    price: 12500,
    description: "탕수육 + 짬뽕 반반",
  },
  {
    id: "tang-bokk",
    name: "탕볶",
    category: "반반메뉴",
    price: 13500,
    description: "탕수육 + 볶음밥 반반",
  },
  {
    id: "kkanpungyuk-jjajang",
    name: "깐풍육짜장",
    category: "반반메뉴",
    price: 13500,
    description: "깐풍육 + 짜장면 반반",
  },
  {
    id: "kkanpungyuk-jjamppong",
    name: "깐풍육짬뽕",
    category: "반반메뉴",
    price: 13500,
    description: "깐풍육 + 짬뽕 반반",
  },
  {
    id: "kkanpungyuk-friedrice",
    name: "깐풍육볶음밥",
    category: "반반메뉴",
    price: 14500,
    description: "깐풍육 + 볶음밥 반반",
  },
  {
    id: "jjam-ja",
    name: "짬짜",
    category: "반반메뉴",
    price: 10500,
    description: "짬뽕 + 짜장면 반반",
  },
  {
    id: "bokk-ja",
    name: "볶짜",
    category: "반반메뉴",
    price: 11500,
    description: "볶음밥 + 짜장면 반반",
  },
  {
    id: "bokk-jjam",
    name: "볶짬",
    category: "반반메뉴",
    price: 11500,
    description: "볶음밥 + 짬뽕 반반",
  },

  // 세트메뉴
  {
    id: "set-tangsuyuk-jjajang",
    name: "탕수육+짜장",
    category: "세트메뉴",
    price: 24000,
    description: "탕수육과 짜장면 세트",
  },
  {
    id: "set-tangsuyuk-jjamppong",
    name: "탕수육+짬뽕",
    category: "세트메뉴",
    price: 25000,
    description: "탕수육과 짬뽕 세트",
  },
  {
    id: "set-tangsuyuk-shrimprice",
    name: "탕수육+새우볶음밥",
    category: "세트메뉴",
    price: 26000,
    description: "탕수육과 새우볶음밥 세트",
  },
  {
    id: "set-tangsuyuk-jaengban",
    name: "탕수육+쟁반짜장",
    category: "세트메뉴",
    price: 26000,
    description: "탕수육과 쟁반짜장 세트",
  },
  {
    id: "set-tangsuyuk-chadol",
    name: "탕수육+차돌짬뽕",
    category: "세트메뉴",
    price: 28000,
    description: "탕수육과 차돌짬뽕 세트",
  },
  {
    id: "set-tangsuyuk-samsun",
    name: "탕수육+삼선짬뽕",
    category: "세트메뉴",
    price: 28000,
    description: "탕수육과 삼선짬뽕 세트",
  },
  {
    id: "set-tangsuyuk-jjajangjjajang",
    name: "탕수육+짜장짜장",
    category: "세트메뉴",
    price: 29000,
    description: "탕수육과 짜장면 2그릇 세트",
  },
  {
    id: "set-tangsuyuk-jjajangjjamppong",
    name: "탕수육+짜장짬뽕",
    category: "세트메뉴",
    price: 30000,
    description: "탕수육과 짜장면 1그릇, 짬뽕 1그릇 세트",
  },
  {
    id: "set-tangsuyuk-jjamppongjjamppong",
    name: "탕수육+짬뽕짬뽕",
    category: "세트메뉴",
    price: 31000,
    description: "탕수육과 짬뽕 2그릇 세트",
  },
  {
    id: "set-tangsuyuk-japchaerice",
    name: "탕수육+잡채밥",
    category: "세트메뉴",
    price: 27000,
    description: "탕수육과 잡채밥 세트",
  },

  // 요리
  {
    id: "tangsuyuk",
    name: "탕수육",
    category: "요리",
    price: 23000,
    description: "바삭한 튀김에 새콤달콤 소스를 곁들인 탕수육",
  },
  {
    id: "kkanpunggi",
    name: "깐풍기",
    category: "요리",
    price: 26000,
    description: "매콤 달콤 바삭한 닭튀김 요리",
  },
  {
    id: "yuringgi",
    name: "유린기",
    category: "요리",
    price: 36000,
    description: "새콤달콤 특제 소스를 곁들인 담백한 닭튀김",
  },
  {
    id: "yangjangpi",
    name: "양장피",
    category: "요리",
    price: 27000,
    description: "해파리와 각종 고명을 겨자 소스에 버무린 요리",
  },
  {
    id: "yusanseul",
    name: "유산슬",
    category: "요리",
    price: 30000,
    description: "고기와 해물, 야채를 하얀 소스로 볶아낸 요리",
  },
  {
    id: "kkanpungyuk",
    name: "깐풍육",
    category: "요리",
    price: 27000,
    description: "매콤 달콤 바삭한 고기 튀김 요리",
  },
  {
    id: "yurinyuk",
    name: "유린육",
    category: "요리",
    price: 35000,
    description: "새콤달콤 소스를 곁들인 담백한 고기 튀김",
  },
  {
    id: "chilli-shrimp",
    name: "칠리새우",
    category: "요리",
    price: 30000,
    description: "매콤달콤한 칠리소스의 새우 요리",
  },
  {
    id: "cream-shrimp",
    name: "크림새우",
    category: "요리",
    price: 30000,
    description: "고소한 크림소스의 새우 요리",
  },
  {
    id: "kkanpung-shrimp",
    name: "깐풍새우",
    category: "요리",
    price: 30000,
    description: "매콤 달콤 바삭한 새우 튀김 요리",
  },
  {
    id: "gochu-japchae-kkotbbang",
    name: "고추잡채+꽃빵",
    category: "요리",
    price: 37000,
    description: "매콤한 고추잡채와 폭신한 꽃빵",
  },
  {
    id: "haemul-nurungjitang",
    name: "해물누룽지탕",
    category: "요리",
    price: 37000,
    description: "바삭한 누룽지에 얼큰한 해물 소스를 부은 요리",
  },
  {
    id: "nanjawanseu",
    name: "난자완스",
    category: "요리",
    price: 36000,
    description: "큼직한 고기완자를 소스에 조린 요리",
  },
  {
    id: "japchae",
    name: "잡채",
    category: "요리",
    price: 23000,
    description: "당면과 야채를 볶아낸 잡채",
  },
  {
    id: "sacheon-tangsuyuk",
    name: "사천탕수육",
    category: "요리",
    price: 27000,
    description: "매콤한 사천식 소스를 곁들인 탕수육",
  },
  {
    id: "samsun-sulguk",
    name: "삼선술국",
    category: "요리",
    price: 26000,
    description: "해물이 듬뿍 들어간 얼큰한 술국",
  },
];
