services:
  - type: web
    name: rihyang-takeout
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
